tankDynamoStreamHandler:
  handler: handlers/dynamo-streams/tankDynamoStreamHandler.process
  timeout: 900
  tags:
    DEPARTMENT: MACHINERY
    ENVIRONMENT: DEV

  events:
    - existingDynamoStream:
        tableName: Tank
        streamType: NEW_IMAGE
        startingPosition: LATEST
