- hosts: localhost
  tasks:
    - name: Create the S3 Tanks bucket
      s3_bucket:
        name: commandeer-tanks-test
        versioning: yes
        tags:
          name: Tanks
          type: demo
    - name: Upload tank A1 configuration
      aws_s3:
        bucket: commandeer-tanks-test
        object: tanks/a1.json
        src: "./a1.json"
        mode: put
    - name: Create a hangar folder for tanks
      aws_s3:
        bucket: commandeer-tanks-test
        object: tanks/hangar
        mode: create
