service: commandeer-tanks

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 256
  region: us-west-1
  stage: ${opt:stage, 'development'}
  timeout: 30
  versionFunctions: false

plugins:
  - serverless-plugin-typescript

functions:

  # Dynamo Streams
  tankDynamoStreamEvent: ${file(./handlers/dynamo-streams/tankDynamoStreamHandler.yml):tankDynamoStreamHandler}

  # S3 Events
  tankS3FileCreatedEvent: ${file(./handlers/s3/tankS3FileCreatedHandler.yml):tankS3FileCreatedHandler}

  # SQS Events
  tankSqsMessageReceiveEvent: ${file(./handlers/sqs/tankSqsMessageReceivedHandler.yml):tankSqsMessageReceivedHandler}

custom:
  tanksBucket: ${self:service}-${self:provider.stage}-tanks
